spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: excelsior
#      username: admin
#      password: password
#      authentication-database: admin

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
